### ISSUE TITLE
Errors returned from getWhois.php

### ISSUE THREAD

**Issue by MikeDpicks** [bulbajackel/SPFtoolbox#4]
Upon calling the getWhois.php file some error messages are returned in the response:

1) ( ! ) Notice: Undefined variable: out in C:\wamp64\www\spf\getWhois.php on line 7

2) ( ! ) Warning: Illegal string offset 'handler' in C:\wamp64\www\spf\phpwhois\whois.gtld.php on line 57

- Seems to happen regardless of the domain called
- Easy to repro

![screenshot_1](https://user-images.githubusercontent.com/21197268/28502264-8a6b5dae-6fb4-11e7-8139-a2a95b8aa540.png)

**Comment by bulbajackel** [comment]
I am somehow not receiving this.  Can you try out the changes on the feature/errors branch?

**Comment by bulbajackel** [comment]
Just did another commit, I updated the version of PHP Whois I was using and simplified the file.
